// Placeholder for generated worklet bundle
// This file is generated by running: npm run build:worklet
// The actual bundle will be created at: wdk-secret-manager-worklet.bundle.js

export default {};

